name: Deploy Application

# Define trigger
on:
    push:
        branches:
            - master

# prepare app so its ready, compile css, js, and install composer dependencies
jobs:
  create-deployment-artifacts:
          name: Create deployment artifacts
          # runner
          runs-on: ubuntu-latest
          # let github see and use our deployment matrix
          outputs: 
            deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
          # use action provided by github
          steps:
              - uses: actions/checkout@v2
            
              - name: Compile CSS and Javascript
                # install npm dependencies, then compile css and js
                run: |
                    npm install
                    npm run prod

              # configure runner with right php version
              - name: Configure PHP 7.4
                uses: shivammathur/setup-php@master
                with:
                    php-version: 7.4
                    extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

              # install composer dependencies
              - name: Install Composer Dependencies
                run: composer install --no-dev --no-interaction --prefer-dist

              # create archive of the entire app
              - name: Create Deployment Artifact 
              # checkout documentation to see props we can reference on github
                env:
                  GITHUB_SHA: ${{ github.sha }}
                run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules *
              # identify each release, using a github hash action

              # store artifact for distribution
              - name: Store Artifact for Distribution
                # github action to upload build artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: app-build
                    path: ${{ github.sha }}.tar.gz

              # export deloyment matrix
              - name: Export Deployment Matrix
                id: export-deployment-matrix
                run: |
                  JSON="$(cat ./deployment-config.json)"
                  JSON="${JSON//'%'/'%25'}"
                  JSON="${JSON//$'\n'/'%0A'}"
                  JSON="${JSON//$'\r'/'%0D'}"
                  echo "::set-output name=deployment-matrix::$JSON"

  # prepare release on the server
  prepare-release-on-server:
          runs-on: ubuntu-latest
          needs: create-deployment-artifacts
          strategy:
            matrix: 
            #think of matrix like an array
              server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
            #steps for this job
          steps:
            - uses: actions/download-artifact@v2
              with: 
                name: app-build
          # use repository secrets and SSH keys when in production
          #upload files to server
            - name: Upload File to Server
              uses: appleboy/scp-action@master
              with: 
                host: ${{ matrix.server.ip }}
                username: ${{ matrix.server.username }}
                password: ${{ matrix.server.password }}
                port: ${{ matrix.server.port }} 
                # my thought is I can upload untar this file directly to the current or html folder without having to upload it on there, whats the point
                source: ${{ github.sha }}.tar.gz
                target: ${{ matrix.server.path }}/artifacts
                # maybe philo is crazy, but in the blog he didnt add the xtra line // /var/www/html/artifacts, I didn't get the cannot found error after I removed this line

            # extract it, so we have a release to actually work with
            - name: Extract Archives & Create New Di rectories
              # use appleboy action
              uses: appleboy/ssh-action@master
              env:
                  GITHUB_SHA: ${{ github.sha }}
              with:
                host: ${{ matrix.server.ip }}
                username: ${{ matrix.server.username }}
                password: ${{ matrix.server.password }}
                port: ${{ matrix.server.port }} 
                envs: GITHUB_SHA
                # at this point files get extracted and placed on the releases folder * note this place *
                # Share storage between different releases, we don't want to override server files, so we remove it from our release
                script: |
                  mkdir -p "${{ matrix.server.path }}/releases/${GITHUB_SHA}"
                  tar xzf ${{ matrix.server.path }}/artifacts/${GITHUB_SHA}.tar.gz -C "${{ matrix.server.path }}/releases/${GITHUB_SHA}"
                  
                  rm -rf ${{ matrix.server.path }}/releases/${GITHUB_SHA}/storage
                  mkdir -p ${{ matrix.server.path }}/storage/{app,public,framework,logs}
                  mkdir -p ${{ matrix.server.path }}/storage/framework/{cache,sessions,testing,views}
                  mkdir -p ${{ matrix.server.path }}/storage/framework/cache/data
                  chmod -R 0777 ${{ matrix.server.path }}/storage

  # these hooks in the script tied to the deployment config are run before an app is released on our server
  run-before-hooks:
          name: "${{ matrix.server.name }}: Before Release Hook"
          runs-on: ubuntu-latest
          needs: [ create-deployment-artifacts, prepare-release-on-server ]
          strategy:
            matrix:
              server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
          steps:
          - name: Run Before Hooks
            uses: appleboy/ssh-action@master
            env:
              GITHUB_SHA: ${{ github.sha }}
              RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
              ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
              STORAGE_PATH: ${{ matrix.server.path }}/storage
              BASE_PATH: ${{ matrix.server.path }}
            with:
              host: ${{ matrix.server.ip }}
              username: ${{ matrix.server.username }}
              password: ${{ matrix.server.password }}
              port: ${{ matrix.server.port }}
              envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
              # these hooks in the script tied to the deployment config are run before an app is released on our server
              script: |
                ${{ matrix.server.beforeHooks }}

  # activate our release
  activate-release:
          name: "${{ matrix.server.name }}: Activate Release"
          runs-on: ubuntu-latest
          needs: [ create-deployment-artifacts, prepare-release-on-server, run-before-hooks ]
          strategy:
            matrix:
              server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
          steps:
          - name: Activate Release
            uses: appleboy/ssh-action@master
            env:
              GITHUB_SHA: ${{ github.sha }}
              RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
              ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
              STORAGE_PATH: ${{ matrix.server.path }}/storage
              BASE_PATH: ${{ matrix.server.path }}
              LARAVEL_ENV: ${{ secrets.LARAVEL_ENV }}
            with:
              host: ${{ matrix.server.ip }}
              username: ${{ matrix.server.username }}
              password: ${{ matrix.server.password }}
              port: ${{ matrix.server.port }}
              envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH,LARAVEL_ENV
              # make sure current dir is pointing to new release by symlinking
              # he used php 8.0 and it worked for him, I don't understand, we installed the same nginx version
              # printf echo secrets content
              #01 - to make this work we then changed our php server provisioning to 8.0, I doubt if this was the error, because laravel is configured to 7.4
              #nope 01 did not work
              #02 - Invalid cache path, create add dir inside framework->cache->data
              script: |
                printf "%s" "$LARAVEL_ENV" > "${BASE_PATH}/.env"
                ln -s -f ${BASE_PATH}/.env $RELEASE_PATH
                ln -s -f $STORAGE_PATH $RELEASE_PATH
                ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
                service php7.4-fpm reload

  # these hooks in the script tied to the deployment config are run after an app is released on our server
  run-after-hooks:
          name: "${{ matrix.server.name }}: After Release Hook"
          runs-on: ubuntu-latest
          needs: [ create-deployment-artifacts, prepare-release-on-server, activate-release ]
          strategy:
            matrix:
              server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
          steps:
          - name: Run After Hooks
            uses: appleboy/ssh-action@master
            env:
              GITHUB_SHA: ${{ github.sha }}
              RELEASE_PATH: ${{ matrix.server.path }}/releases/${{ github.sha }}
              ACTIVE_RELEASE_PATH: ${{ matrix.server.path }}/current
              STORAGE_PATH: ${{ matrix.server.path }}/storage
              BASE_PATH: ${{ matrix.server.path }}
            with:
              host: ${{ matrix.server.ip }}
              username: ${{ matrix.server.username }}
              password: ${{ matrix.server.password }}
              port: ${{ matrix.server.port }}
              envs: GITHUB_SHA,RELEASE_PATH,ACTIVE_RELEASE_PATH,STORAGE_PATH,BASE_PATH
              # these hooks in the script tied to the deployment config are run before an app is released on our server
              script: |
                ${{ matrix.server.afterHooks }}

  clean-up:
        name: "${{ matrix.server.name }}: Clean up"
        runs-on: ubuntu-latest
        needs: [ create-deployment-artifacts, prepare-release-on-server, activate-release, run-after-hooks ]
        strategy:
          matrix:
            server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
        steps:
        - name: Clean Up
          uses: appleboy/ssh-action@master
          env:
            RELEASES_PATH: ${{ matrix.server.path }}/releases
            ARTIFACTS_PATH: /var/www/artifacts
          with:
            host: ${{ matrix.server.ip }}
            username: ${{ matrix.server.username }}
            password: ${{ matrix.server.password }}
            port: ${{ matrix.server.port }}
            envs: RELEASES_PATH, ARTIFACTS_PATH
            # use tail command to offset list by 5 and return any rem dirs 
            script: |
              cd $RELEASES_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
              cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf